### ISSUE TITLE
cpp08/ex00

### ISSUE THREAD

**Issue by manuel-aguiar** [MariaAguiar/cpps#1]
"
template<typename T>
void easyfind(T t, int n)
{
	int pos = std::distance(t.begin(), std::find(t.begin(), t.end(), n));
	if (pos != (int)t.size())
	{
		std::cout << "Number " << n << " found in the provided container at position " \
		<< ++pos << "." << std::endl;
	}
	else
		std::cout << "Number " << n << " is not in the provided container." << std::endl;
}
"

easyfind, melhor receber uma referencia:
void easyfind(T& t, int n)
-> se não, possivelmente o compilador vai fazer uma copia do object inteiro para fazer a função e nao vale a pena
(o compilador pode sempre tentar optimizar, mas passa referencia just in case)

Podes simplificar a procura, mesmo que te queiras precaver para a std::stack (que tecnicamente é um "adapter" e não um "trv3" container), a stack nao tem .begin() (nao tem iteradores!)
Podes fazer por exemplo:

typename T::iterator iter = std::find(t.begin(), t.end(), n)) // retornar o iterator onde está esse objecto que procuras
if (iter == t.end())     //iter vai apontar para o sentinel .end() se nao encontrar o objecto no container
    blabla nao encontrei
else
   tá aqui!

Sempre é mais curtinho e faz o mesmo :) e diria que é stl algorithms o suficiente

**Comment by MariaAguiar** [comment]
Thank you!
